### PR TITLE
Maintenance (#149)

### PR DESCRIPTION
**Pull request by neilstevenson**
Retire demos moving to https://github.com/hazelcast-guides

### CODE REVIEW

**Review by jondiamond — APPROVED** [review]
Reviewed changes / redirects to hazelcast-guides

**Review by johnmdesjardins — APPROVED** [review]
Reviewed and approve

**Comment by johnmdesjardins** [comment]
Squash and merge

**Comment by johnmdesjardins** [comment]
Squash and merge

**Pull request merged**
